version: "3.9"

services:
  app:
    build:
      dockerfile: dockerfile-app
      context: .
    working_dir: /app
    volumes:
      - ./:/app
    command: "node start.js"
  app-interval:
    container_name: appInterval
    build:
      dockerfile: dockerfile-app-interval
      context: .
    working_dir: /app-interval
    volumes:
      - ./:/app-interval
    command: "node startInterval.js"